In [1]:
import pyodbc
connection = pyodbc.connect('Driver={SQL Server};'
                                'Server=DESKTOP-###;'
                                'Database=AdventureWorks2017;'
                                'Trusted_Connection=True;')

cursor = connection.cursor()

In [2]:
import pandas as pd
import pandas.io.sql as psql
import pandas as pd
import numpy as np
from pandasql import *
pysqldf = lambda q: sqldf(q, locals())

In [3]:
query = '''SELECT * FROM Purchasing.PurchaseOrderDetail'''
df = pd.read_sql(query, connection)
df

PurchaseOrderID  PurchaseOrderDetailID    DueDate  OrderQty  ProductID  \
0                   1                      1 2011-04-30         4          1   
1                   2                      2 2011-04-30         3        359   
2                   2                      3 2011-04-30         3        360   
3                   3                      4 2011-04-30       550        530   
4                   4                      5 2011-04-30         3          4   
...               ...                    ...        ...       ...        ...   
8840             4011                   8841 2014-07-24      1000        880   
8841             4012                   8842 2014-07-24      6000        881   
8842             4012                   8843 2014-07-24      6000        882   
8843             4012                   8844 2014-07-24      6000        883   
8844             4012                   8845 2014-07-24      6000        884   

      UnitPrice    LineTotal  ReceivedQty  RejectedQty  StockedQty  \
0       50.2600     201.0400          3.0          0.0         3.0   
1       45.1200     135.3600          3.0          0.0         3.0   
2       45.5805     136.7415          3.0          0.0         3.0   
3       16.0860    8847.3000        550.0          0.0       550.0   
4       57.0255     171.0765          2.0          1.0         1.0   
...         ...          ...          ...          ...         ...   
8840    20.5600   20560.0000       1000.0          0.0      1000.0   
8841    41.5700  249420.0000       6000.0          0.0      6000.0   
8842    41.5700  249420.0000       6000.0          0.0      6000.0   
8843    41.5700  249420.0000       6000.0          0.0      6000.0   
8844    41.5700  249420.0000       6000.0          0.0      6000.0   

                ModifiedDate  
0    2011-04-23 00:00:00.000  
1    2011-04-23 00:00:00.000  
2    2011-04-23 00:00:00.000  
3    2011-04-23 00:00:00.000  
4    2011-04-23 00:00:00.000  
...                      ...  
8840 2015-08-12 12:25:46.470  
8841 2015-08-12 12:25:46.483  
8842 2015-08-12 12:25:46.483  
8843 2015-08-12 12:25:46.483  
8844 2015-08-12 12:25:46.483  

[8845 rows x 11 columns]

In [12]:
df=np.array(pd.read_sql(query, connection))

In [13]:
df

array([[1, 1, Timestamp('2011-04-30 00:00:00'), ..., 0.0, 3.0,
        Timestamp('2011-04-23 00:00:00')],
       [2, 2, Timestamp('2011-04-30 00:00:00'), ..., 0.0, 3.0,
        Timestamp('2011-04-23 00:00:00')],
       [2, 3, Timestamp('2011-04-30 00:00:00'), ..., 0.0, 3.0,
        Timestamp('2011-04-23 00:00:00')],
       ...,
       [4012, 8843, Timestamp('2014-07-24 00:00:00'), ..., 0.0, 6000.0,
        Timestamp('2015-08-12 12:25:46.483000')],
       [4012, 8844, Timestamp('2014-07-24 00:00:00'), ..., 0.0, 6000.0,
        Timestamp('2015-08-12 12:25:46.483000')],
       [4012, 8845, Timestamp('2014-07-24 00:00:00'), ..., 0.0, 6000.0,
        Timestamp('2015-08-12 12:25:46.483000')]], dtype=object)

In [14]:
query = '''SELECT UnitPrice FROM Purchasing.PurchaseOrderDetail'''
df = pd.read_sql(query, connection)
df

UnitPrice
0       50.2600
1       45.1200
2       45.5805
3       16.0860
4       57.0255
...         ...
8840    20.5600
8841    41.5700
8842    41.5700
8843    41.5700
8844    41.5700

[8845 rows x 1 columns]

In [15]:
df=np.array(pd.read_sql(query, connection))
df

array([[50.26  ],
       [45.12  ],
       [45.5805],
       ...,
       [41.57  ],
       [41.57  ],
       [41.57  ]])

Let's find maximum price

In [21]:
max(df)

array([82.8345])

Let's find mininum price.

In [22]:
min(df)

array([0.21])

Let's find mean of array.

In [27]:
df.mean()

34.74296411531939

Let's find look at the results horizontally.

In [44]:
np.hstack(df)

array([50.26  , 45.12  , 45.5805, ..., 41.57  , 41.57  , 41.57  ])

Let's find the median value of array.

In [45]:
np.median(df)

39.2805

In [109]:
df

0  307301.5176

In [110]:
np.sum(df)

    307301.5176
dtype: float64

Now let's check these results with sql.

In [46]:
#max value
query = '''SELECT max(UnitPrice) FROM Purchasing.PurchaseOrderDetail'''
df = pd.read_sql(query, connection)
df

0  82.8345

In [47]:
#min value
query = '''SELECT min(UnitPrice) FROM Purchasing.PurchaseOrderDetail'''
df = pd.read_sql(query, connection)
df

0  0.21

In [49]:
# mean
query = '''SELECT avg(UnitPrice) FROM Purchasing.PurchaseOrderDetail''' 
df = pd.read_sql(query, connection)
df

0  34.7429

In [99]:
#number of rows
query = '''SELECT count(UnitPrice) FROM Purchasing.PurchaseOrderDetail''' 
df = pd.read_sql(query, connection)
df

0  8845

In [105]:
#median value
query = '''SELECT PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY UnitPrice) OVER() FROM Purchasing.PurchaseOrderDetail ''' 
df = pd.read_sql(query, connection)
df

0     39.2805
1     39.2805
2     39.2805
3     39.2805
4     39.2805
...       ...
8840  39.2805
8841  39.2805
8842  39.2805
8843  39.2805
8844  39.2805

[8845 rows x 1 columns]

In [108]:
#sum
query = '''SELECT SUM(UnitPrice) FROM Purchasing.PurchaseOrderDetail''' 
df = pd.read_sql(query, connection)
df

0  307301.5176